config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :admins
  root 'landing#index'
  resources :about, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    render :index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    render :index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.json
  def index
    @projects = HTTParty.get("https://api.github.com/users/lorenglenn/repos?per_page=100&access_token=" + ENV['AUTH_TOKEN'],
                            headers: {"User-Agent" => "github-prac"
                                      })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<h3>How I became a Junior Developer:</h3>

<h4>
  Insert story here about struggles growing up in the Bronx. Fighting for every meal, just to survive. Met Bill Gates
at a Chipotle and he opened my eyes to the world of technology.
</h4>

app/views/landing/index.html.erb
<h1>Welcome to Loren Glenn's Portfolio</h1>
<div class="landing-image">
  <%= image_tag("https://c.tadst.com/gfx/750w/international-programmer-day.jpg?1") %><br>
  <small> - this image isn't me!</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loren Glenn</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class = "nav navbar navbar-inverse shift">
      <%= link_to "Loren Glenn", root_path %> |
      <%= link_to "Projects", projects_path %> |
      <%= link_to "About", about_index_path %>
      <div class="pull-right shift">
        <% if current_admin %>
        Logged in as Admin</li>
        <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span> <%= link_to "Log-out", destroy_admin_session_path, method: "delete" %>
        <% else %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        <%= link_to "Log in as Admin", new_admin_session_path %></a> |
        <%= link_to "New Admin", new_admin_registration_path %></a>
        <% end %>
      </div>
    </nav>
        <div class="container">
          <div class="alert-warning">
          <%= flash[:alert] %>
          <%= flash[:notice] %>
        </div>
          <%= yield %>
      </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>
<h3>Click a project to view on Github</h3>
  <div class="row">
    <% @projects.each do |project| %>
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Project Name: <%= link_to project["name"], "https://github.com/lorenglenn/" + project["name"] %>
        </div>
        <div class="panel-body">
            Description: <%= project["description"] %>
        </div>
      </div>
    </div>
    <% end %>
    <hr>
  </div>